export const BUILDING_WIDTH = 125;
export const BUILDING_HEIGHT = BUILDING_WIDTH * 1.5;
export const CARD_MARGIN = 20;
export const WONDER_WIDTH = BUILDING_HEIGHT * 1.5;
export const WONDER_HEIGHT = BUILDING_HEIGHT;
export const BOARD_WIDTH = 1680;
export const BOARD_HEIGHT = 1200;
export const MAX_CARDS = 20;
export const PROGESS_BOARD_WIDTH = 200;
export const PROGESS_BOARD_HEIGHT = PROGESS_BOARD_WIDTH * 3.525
export const MAX_COINS_6 = 7;
export const MAX_COINS_3 = 9;
export const MAX_COINS_1 = 14;
export const COIN_WIDTH_6 = 100;
export const COIN_WIDTH_3 = 75;
export const COIN_WIDTH_1 = 60;
